export const UPLOAD_IMAGE = "UPLOAD_IMAGE";
export const UPLOAD_IMAGE_SUCCESS = "UPLOAD_IMAGE_SUCCESS";
export const UPLOAD_IMAGE_FAILURE = "UPLOAD_IMAGE_FAILURE";

export const GET_TEXT_FROM_IMAGE = "GET_TEXT_FROM_IMAGE";
export const GET_TEXT_FROM_IMAGE_SUCCESS = "GET_TEXT_FROM_IMAGE_SUCCESS";
export const GET_TEXT_FROM_IMAGE_FAILURE = "GET_TEXT_FROM_IMAGE_FAILURE";
